version: '3'
services:
  bookon:
    image: bookon
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - ./src:/var/app/src
